import { makeStyles } from 'tss-react/mui';

const CORAL = '#D35F55';
const CORAL_LIGHT = '#fdf1f0';
const SIDEBAR_WIDTH = 220;

export const useDashboardStyles = makeStyles()({
  root: {
    display: 'flex',
    height: '100vh',
    width: '100vw',
    overflow: 'hidden',
    fontFamily: '"Georgia", serif',
    backgroundColor: '#f7f7f5',
  },

  // ── Sidebar ──────────────────────────────────────────────────────────────
  sidebar: {
    width: SIDEBAR_WIDTH,
    minWidth: SIDEBAR_WIDTH,
    backgroundColor: '#ffffff',
    borderRight: '1px solid #ebebeb',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '1px 0 8px rgba(0,0,0,0.04)',
  },
  logoRow: {
    display: 'flex',
    alignItems: 'center',
    padding: '20px 20px 16px',
    gap: '10px',
  },
  logoAvatar: {
    width: 34,
    height: 34,
    borderRadius: '10px',
    backgroundColor: CORAL,
    color: '#fff',
    fontWeight: 700,
    fontSize: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  logoText: {
    fontWeight: 700,
    fontSize: '17px',
    color: '#1a1a1a',
    letterSpacing: '-0.3px',
  },
  sidebarDivider: {
    height: '1px',
    backgroundColor: '#f0f0f0',
    margin: '0 0 12px',
  },
  navLabel: {
    fontSize: '10px',
    fontWeight: 700,
    color: '#aaa',
    letterSpacing: '0.08em',
    padding: '0 20px',
    marginBottom: '6px',
  },
  nav: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
    padding: '0 10px',
  },
  navItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '9px 12px',
    borderRadius: '8px',
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    fontSize: '13.5px',
    color: '#555',
    fontFamily: 'Georgia, serif',
    textAlign: 'left' as const,
    width: '100%',
    transition: 'background 0.15s, color 0.15s',
  },
  navItemActive: {
    backgroundColor: CORAL_LIGHT,
    color: CORAL,
    fontWeight: 600,
  },
  navIcon: {
    fontSize: '13px',
    width: '16px',
    textAlign: 'center' as const,
    flexShrink: 0,
  },
  navBadge: {
    marginLeft: 'auto',
    backgroundColor: CORAL,
    color: '#fff',
    borderRadius: '10px',
    fontSize: '11px',
    fontWeight: 700,
    padding: '1px 7px',
  },

  // ── Main ─────────────────────────────────────────────────────────────────
  main: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    padding: '0 28px',
    height: 56,
    backgroundColor: '#ffffff',
    borderBottom: '1px solid #ebebeb',
    gap: '14px',
    flexShrink: 0,
  },
  headerSpacer: {
    flex: 1,
  },
  newTaskBtn: {
    backgroundColor: CORAL,
    color: '#fff',
    border: 'none',
    borderRadius: '8px',
    padding: '8px 18px',
    fontSize: '13.5px',
    fontWeight: 600,
    fontFamily: 'Georgia, serif',
    cursor: 'pointer',
  },

  // ── Profile ───────────────────────────────────────────────────────────────
  profileWrapper: {
    position: 'relative' as const,
  },
  profileBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    background: 'transparent',
    border: '1px solid #ebebeb',
    borderRadius: '20px',
    padding: '5px 12px 5px 6px',
    cursor: 'pointer',
  },
  profileAvatar: {
    width: 28,
    height: 28,
    borderRadius: '50%',
    backgroundColor: CORAL,
    color: '#fff',
    fontSize: '11px',
    fontWeight: 700,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  profileName: {
    fontSize: '13px',
    color: '#333',
  },
  profileDropdown: {
    position: 'absolute' as const,
    top: 'calc(100% + 8px)',
    right: 0,
    backgroundColor: '#fff',
    border: '1px solid #ebebeb',
    borderRadius: '12px',
    boxShadow: '0 8px 24px rgba(0,0,0,0.10)',
    width: 220,
    zIndex: 100,
    overflow: 'hidden' as const,
  },
  dropdownHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '14px 16px',
  },
  dropdownAvatar: {
    width: 36,
    height: 36,
    borderRadius: '50%',
    backgroundColor: CORAL,
    color: '#fff',
    fontSize: '13px',
    fontWeight: 700,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  dropdownName: {
    margin: 0,
    fontSize: '13px',
    fontWeight: 600,
    color: '#1a1a1a',
  },
  dropdownEmail: {
    margin: 0,
    fontSize: '11px',
    color: '#999',
  },
  dropdownDivider: {
    height: '1px',
    backgroundColor: '#f0f0f0',
  },
  dropdownItem: {
    display: 'block',
    width: '100%',
    padding: '11px 16px',
    background: 'transparent',
    border: 'none',
    textAlign: 'left' as const,
    fontSize: '13px',
    color: '#444',
    cursor: 'pointer',
  },
  dropdownOverlay: {
    position: 'fixed' as const,
    inset: 0,
    zIndex: 99,
  },

  // ── Content ───────────────────────────────────────────────────────────────
  content: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: '32px 40px',
  },
});
