import { makeStyles } from 'tss-react/mui';

import { CORAL, CORAL_LIGHT } from '@/models/color';

const SIDEBAR_WIDTH = 220;
const HEADER_HEIGHT = 71;

export const useDashboardStyles = makeStyles()({
  root: {
    display: 'block',
    minHeight: '100dvh',
    width: '100%',
    maxWidth: '100%',
    fontFamily: '"Georgia", serif',
    backgroundColor: '#f7f7f5',
    '@media (max-width: 900px)': {
      flexDirection: 'column',
    },
  },

  // ── Sidebar ──────────────────────────────────────────────────────────────
  sidebar: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    bottom: 0,
    zIndex: 20,
    width: SIDEBAR_WIDTH,
    minWidth: SIDEBAR_WIDTH,
    backgroundColor: '#ffffff',
    borderRight: '1px solid #ebebeb',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: 'none',
    marginLeft: 0,
    paddingLeft: 0,
    '@media (max-width: 900px)': {
      position: 'relative' as const,
      top: 'auto',
      left: 'auto',
      bottom: 'auto',
      zIndex: 'auto',
      width: '100%',
      minWidth: 0,
      borderRight: 'none',
      borderBottom: '1px solid #ebebeb',
    },
  },
  logoRow: {
    display: 'flex',
    alignItems: 'center',
    padding: '20px 0 16px 0',
    gap: '10px',
    marginLeft: 12,
  },
  logoAvatar: {
    width: 34,
    height: 34,
    borderRadius: '10px',
    backgroundColor: CORAL,
    color: '#fff',
    fontWeight: 700,
    fontSize: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  logoText: {
    fontWeight: 700,
    fontSize: '17px',
    color: '#1a1a1a',
    letterSpacing: '-0.3px',
  },
  sidebarDivider: {
    height: '1px',
    backgroundColor: '#f0f0f0',
    margin: '0 0 12px',
  },
  navLabel: {
    fontSize: '10px',
    fontWeight: 700,
    color: '#aaa',
    letterSpacing: '0.08em',
    padding: '0',
    marginLeft: 12,
    marginBottom: '6px',
  },
  nav: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
    padding: '0',
    marginLeft: 12,
  },
  navItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '9px 8px 9px 0',
    borderRadius: '8px',
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    fontSize: '13.5px',
    color: '#555',
    fontFamily: 'Georgia, serif',
    textAlign: 'left' as const,
    width: '100%',
    transition: 'background 0.15s, color 0.15s',
  },
  navItemActive: {
    backgroundColor: CORAL_LIGHT,
    color: CORAL,
    fontWeight: 600,
  },
  navIcon: {
    fontSize: '13px',
    width: '16px',
    textAlign: 'center' as const,
    flexShrink: 0,
  },
  navBadge: {
    marginLeft: 'auto',
    backgroundColor: CORAL,
    color: '#fff',
    borderRadius: '10px',
    fontSize: '11px',
    fontWeight: 700,
    padding: '1px 7px',
  },

  // ── Main ─────────────────────────────────────────────────────────────────
  main: {
    display: 'flex',
    flexDirection: 'column',
    minWidth: 0,
    marginLeft: SIDEBAR_WIDTH,
    minHeight: '100dvh',
    overflow: 'hidden',
    '@media (max-width: 900px)': {
      marginLeft: 0,
      minHeight: 'auto',
    },
  },
  header: {
    position: 'fixed' as const,
    top: 0,
    left: SIDEBAR_WIDTH,
    right: 0,
    zIndex: 30,
    display: 'flex',
    alignItems: 'center',
    padding: '0 28px',
    height: HEADER_HEIGHT,
    backgroundColor: '#ffffff',
    borderBottom: '1px solid #ebebeb',
    gap: '14px',
    flexShrink: 0,
    '@media (max-width: 900px)': {
      position: 'relative' as const,
      top: 'auto',
      left: 'auto',
      right: 'auto',
      zIndex: 'auto',
      padding: '0 16px',
    },
  },
  headerSpacer: {
    flex: 1,
  },
  newTaskBtn: {
    backgroundColor: CORAL,
    color: '#fff',
    border: 'none',
    borderRadius: '8px',
    padding: '8px 18px',
    fontSize: '13.5px',
    fontWeight: 600,
    fontFamily: 'Georgia, serif',
    cursor: 'pointer',
  },

  // ── Profile ───────────────────────────────────────────────────────────────
  profileWrapper: {
    position: 'relative' as const,
  },
  profileBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    background: 'transparent',
    border: '1px solid #ebebeb',
    borderRadius: '20px',
    padding: '5px 12px 5px 6px',
    cursor: 'pointer',
  },
  profileAvatar: {
    width: 28,
    height: 28,
    borderRadius: '50%',
    backgroundColor: CORAL,
    color: '#fff',
    fontSize: '11px',
    fontWeight: 700,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  profileName: {
    fontSize: '13px',
    color: '#333',
    '@media (max-width: 520px)': {
      display: 'none',
    },
  },
  profileDropdown: {
    position: 'absolute' as const,
    top: 'calc(100% + 8px)',
    right: 0,
    backgroundColor: '#fff',
    border: '1px solid #ebebeb',
    borderRadius: '12px',
    boxShadow: '0 8px 24px rgba(0,0,0,0.10)',
    width: 220,
    zIndex: 100,
    overflow: 'hidden' as const,
  },
  dropdownHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '14px 16px',
  },
  dropdownAvatar: {
    width: 36,
    height: 36,
    borderRadius: '50%',
    backgroundColor: CORAL,
    color: '#fff',
    fontSize: '13px',
    fontWeight: 700,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  dropdownName: {
    margin: 0,
    fontSize: '13px',
    fontWeight: 600,
    color: '#1a1a1a',
  },
  dropdownEmail: {
    margin: 0,
    fontSize: '11px',
    color: '#999',
  },
  dropdownDivider: {
    height: '1px',
    backgroundColor: '#f0f0f0',
  },
  dropdownItem: {
    display: 'block',
    width: '100%',
    padding: '11px 16px',
    background: 'transparent',
    border: 'none',
    textAlign: 'left' as const,
    fontSize: '13px',
    color: '#444',
    cursor: 'pointer',
  },
  dropdownOverlay: {
    position: 'fixed' as const,
    inset: 0,
    zIndex: 10,
  },

  // ── Focus Timer header button ─────────────────────────────────────────────
  focusTimerHeaderBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    border: `1px solid ${CORAL}`,
    borderRadius: '8px',
    padding: '7px 14px',
    fontSize: '12.5px',
    fontWeight: 600,
    fontFamily: 'Georgia, serif',
    cursor: 'pointer',
    color: CORAL,
    backgroundColor: 'transparent',
    flexShrink: 0,
  },
  focusTimerHeaderBtnActive: {
    backgroundColor: CORAL,
    color: '#fff',
    animation: 'focusTimerPulse 1.5s ease-in-out infinite',
  },

  // ── Content ───────────────────────────────────────────────────────────────
  content: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: 'calc(32px + 71px) 40px 32px',
    minHeight: '100dvh',
    '@media (max-width: 900px)': {
      padding: '20px 16px',
      minHeight: 'auto',
    },
  },
});
